#THIS ENTIRE UI CLASS IS GENERATED BY CHATGPT


from __future__ import annotations

from dataclasses import asdict, is_dataclass
from datetime import datetime
from typing import Callable, Any, Optional, List

import Database.DB as DB

from DAO.BrandDAO import BrandDAO
from DAO.CarDAO import CarDAO
from DAO.CustomerDAO import CustomerDAO
from DAO.ContractDAO import ContractDAO
from DAO.Contract_carDAO import Contract_carDAO

from Objects.Brand import Brand
from Objects.Car import Car
from Objects.Customer import Customer
from Objects.Contract import Contract
from Objects.Contract_car import Contract_car


# ----------------------------
# Helpers (simple + forgiving)
# ----------------------------

def prompt_str(label: str, allow_empty: bool = False) -> str:
    while True:
        s = input(f"{label}: ").strip()
        if s or allow_empty:
            return s
        print("Value cannot be empty.")

def prompt_int(label: str) -> int:
    while True:
        s = input(f"{label}: ").strip()
        try:
            return int(s)
        except ValueError:
            print("Please enter an integer (e.g., 12).")

def prompt_float(label: str) -> float:
    while True:
        s = input(f"{label}: ").strip().replace(",", ".")
        try:
            return float(s)
        except ValueError:
            print("Please enter a number (e.g., 123.45).")

def prompt_date_yyyy_mm_dd(label: str) -> datetime:
    # You requested YYYY-MM-DD input.
    while True:
        s = input(f"{label} (YYYY-MM-DD): ").strip()
        try:
            return datetime.strptime(s, "%Y-%m-%d")
        except ValueError:
            print("Invalid date. Example: 2026-01-12")

def prompt_bool_01(label: str, default: Optional[int] = None) -> bool:
    # simplest: 1/0 input
    while True:
        suffix = f" [default {default}]" if default is not None else ""
        s = input(f"{label} (1/0){suffix}: ").strip()
        if not s and default is not None:
            return bool(default)
        if s in ("1", "0"):
            return s == "1"
        print("Enter 1 or 0.")

def safe_call(action: Callable[[], Any]) -> None:
    """
    Runs an action. If config/DB/DAO raises an error, prints the message and continues.
    You wanted to display the errors coming from your methods.
    """
    try:
        action()
    except Exception as e:
        print(f"\nERROR: {e}\n")


def print_rows(rows: List[Any]) -> None:
    if not rows:
        print("(empty)")
        return
    for r in rows:
        if is_dataclass(r):
            print(asdict(r))
        else:
            print(r)


# ----------------------------
# CRUD - Brand
# ----------------------------

def add_brand() -> None:
    name = prompt_str("Brand name")
    category = prompt_str("Category (Economy/Standard/Luxury/SUV)")
    b = Brand(name=name, category=category)
    BrandDAO.insert(b)
    print(f"Inserted brand with id_brand={b.id_brand}")

def delete_brand() -> None:
    id_brand = prompt_int("id_brand to delete")
    b = BrandDAO.get_by_id(id_brand)
    if b is None:
        print("Brand not found.")
        return
    ok = BrandDAO.delete(b)
    print("Deleted." if ok else "Nothing deleted (rowcount=0).")


# ----------------------------
# CRUD - Car
# ----------------------------

def add_car() -> None:
    license_plate = prompt_str("License plate")
    model = prompt_str("Model")
    price_per_day = prompt_float("Price per day")
    is_available = prompt_bool_01("Is available", default=1)
    id_brand = prompt_int("id_brand (FK)")

    car = Car(
        license_plate=license_plate,
        model=model,
        price_per_day=price_per_day,
        is_available=is_available,
        id_brand=id_brand,
    )
    CarDAO.insert(car)
    print(f"Inserted car with id_car={car.id_car}")

def delete_car() -> None:
    id_car = prompt_int("id_car to delete")
    car = CarDAO.get_by_id(id_car)
    if car is None:
        print("Car not found.")
        return
    ok = CarDAO.delete(car)
    print("Deleted." if ok else "Nothing deleted (rowcount=0).")


# ----------------------------
# CRUD - Customer
# ----------------------------

def add_customer() -> None:
    name = prompt_str("Name")
    surname = prompt_str("Surname")
    email = prompt_str("Email")
    c = Customer(name=name, surname=surname, email=email)
    CustomerDAO.insert(c)
    print(f"Inserted customer with id_customer={c.id_customer}")

def delete_customer() -> None:
    id_customer = prompt_int("id_customer to delete")
    c = CustomerDAO.get_by_id(id_customer)
    if c is None:
        print("Customer not found.")
        return
    ok = CustomerDAO.delete(c)
    print("Deleted." if ok else "Nothing deleted (rowcount=0).")


# ----------------------------
# CRUD - Contract
# ----------------------------

def add_contract() -> None:
    # You said: total_price is entered by user, no calculations.
    total_price = prompt_float("Total price")
    id_customer = prompt_int("id_customer (FK)")
    date_from = prompt_date_yyyy_mm_dd("Date from")
    date_to = prompt_date_yyyy_mm_dd("Date to")

    contract = Contract(
        total_price=total_price,
        id_customer=id_customer,
        date_from=date_from,
        date_to=date_to,
    )
    ContractDAO.insert(contract)
    print(f"Inserted contract with id_contract={contract.id_contract}")

def delete_contract() -> None:
    id_contract = prompt_int("id_contract to delete")
    c = ContractDAO.get_by_id(id_contract)
    if c is None:
        print("Contract not found.")
        return
    ok = ContractDAO.delete(c)
    print("Deleted." if ok else "Nothing deleted (rowcount=0).")


# ----------------------------
# Rent / Return (your rules)
# ----------------------------

def rent_a_car() -> None:
    """
    User provides id_contract and id_car:
    - insert into contract_car
    - update car.is_available = 0
    """
    DB.global_connection = DB.ConnectionDecorator()
    try:
        rent_a_car_inner()
    except Exception as e:
        DB.global_connection.really_rollback()
        raise RuntimeError(f"Chyba transakce': {str(e)}") from e
    else:
        DB.global_connection.really_commit()
    finally:
        DB.global_connection.really_close()
        DB.global_connection = None



def rent_a_car_inner() -> None:
    id_contract = prompt_int("id_contract")
    id_car = prompt_int("id_car")

    contract = ContractDAO.get_by_id(id_contract)
    if contract is None:
        print("Contract not found.")
        return

    car = CarDAO.get_by_id(id_car)
    if car is None:
        print("Car not found.")
        return

    if not bool(car.is_available):
        print("Car is already not available (is_available=0).")
        return

    link = Contract_car(id_contract=id_contract, id_car=id_car)
    Contract_carDAO.insert(link)

    car.is_available = 0
    CarDAO.update(car)

    print("OK: contract_car inserted and car.is_available set to 0.")

def return_car() -> None:
    """
    Do NOT delete contract_car record.
    Just set car.is_available = 1.
    """
    id_car = prompt_int("id_car to return")

    car = CarDAO.get_by_id(id_car)
    if car is None:
        print("Car not found.")
        return

    car.is_available = 1
    CarDAO.update(car)
    print("OK: car.is_available set to 1.")


# ----------------------------
# Show raw tables
# ----------------------------

def show_table_contents() -> None:
    print("\nChoose table:")
    print("1) brand")
    print("2) car")
    print("3) customer")
    print("4) contract")
    print("5) contract_car")
    choice = prompt_str("Table", allow_empty=False)

    if choice == "1":
        print_rows(BrandDAO.get_all())
    elif choice == "2":
        print_rows(CarDAO.get_all())
    elif choice == "3":
        print_rows(CustomerDAO.get_all())
    elif choice == "4":
        print_rows(ContractDAO.get_all())
    elif choice == "5":
        print_rows(Contract_carDAO.get_all())
    else:
        print("Unknown option.")


# ----------------------------
# Main menu loop
# ----------------------------

MENU = {
    "1": ("Add brand", add_brand),
    "2": ("Delete brand", delete_brand),
    "3": ("Add car", add_car),
    "4": ("Delete car", delete_car),
    "5": ("Add customer", add_customer),
    "6": ("Delete customer", delete_customer),
    "7": ("Add contract", add_contract),
    "8": ("Delete contract", delete_contract),
    "9": ("Rent a car (contract_id + car_id)", rent_a_car),
    "10": ("Return car (car_id)", return_car),
    "11": ("Show table contents (raw)", show_table_contents),
    "0": ("Exit", None),
}

def main() -> None:
    print("=== Car Rental Terminal UI ===")
    while True:
        print("\n--- MENU ---")
        for k, (label, _) in MENU.items():
            print(f"{k}) {label}")

        choice = prompt_str("Select option")
        if choice == "0":
            print("Bye.")
            return

        action = MENU.get(choice)
        if not action:
            print("Unknown option.")
            continue

        _, fn = action
        if fn is None:
            print("Bye.")
            return

        # Must NOT crash: show error message and continue
        safe_call(fn)


if __name__ == "__main__":
    main()
